### ISSUE TITLE
After updating to 8.3.1, unit tests are failing

### ISSUE THREAD

**Issue by upgradingdave** [camunda-community-hub/camunda-8-process-solution-template#72]
I updated the test dependencies as described here: https://github.com/camunda-community-hub/spring-zeebe#writing-test-cases, but when I run the test, I get a class not found, need to research more: 

```
Exception in thread "grpc-default-executor-0" java.lang.NoClassDefFoundError: com/fasterxml/jackson/core/StreamReadConstraints
```

**Comment by upgradingdave** [comment]
Added this explicit dependency and now unit tests are working: https://github.com/camunda-community-hub/camunda-8-process-solution-template/blob/c112fb6bc01ecc74105a639916da1ced08557794/pom.xml#L62
